import { loader } from "fumadocs-core/source";
import { toFumadocsSource } from "fumadocs-mdx/runtime/server";
// Generated by fumadocs-mdx postinstall — re-run `pnpm postinstall` if missing
import { docs, meta } from "../.source/server";

export const source = loader({
  baseUrl: "/docs",
  source: toFumadocsSource(docs, meta),
});

